import 'package:flutter/material.dart';

class CountrySearch extends SearchDelegate<String> {
  final countryList = [
    "World",
    "USA",
    "India",
    "Brazil",
    "Russia",
    "France",
    "UK",
    "Turkey",
    "Argentina",
    "Colombia",
    "Spain",
    "Italy",
    "Iran",
    "Germany",
    "Indonesia",
    "Poland",
    "Mexico",
    "South Africa",
    "Ukraine",
    "Peru",
    "Netherlands",
    "Czechia",
    "Iraq",
    "Chile",
    "Philippines",
    "Canada",
    "Bangladesh",
    "Malaysia",
    "Belgium",
    "Sweden",
    "Romania",
    "Pakistan",
    "Portugal",
    "Japan",
    "Israel",
    "Hungary",
    "Jordan",
    "Serbia",
    "Switzerland",
    "Nepal",
    "UAE",
    "Austria",
    "Morocco",
    "Thailand",
    "Tunisia",
    "Kazakhstan",
    "Lebanon",
    "Saudi Arabia",
    "Greece",
    "Ecuador",
    "Bolivia",
    "Paraguay",
    "Belarus",
    "Panama",
    "Bulgaria",
    "Georgia",
    "Costa Rica",
    "Kuwait",
    "Cuba",
    "Slovakia",
    "Uruguay",
    "Guatemala",
    "Croatia",
    "Azerbaijan",
    "Dominican Republic",
    "Denmark",
    "Palestine",
    "Sri Lanka",
    "Venezuela",
    "Myanmar",
    "Ireland",
    "Honduras",
    "Oman",
    "Egypt",
    "Lithuania",
    "Ethiopia",
    "Bahrain",
    "Moldova",
    "Slovenia",
    "Libya",
    "Armenia",
    "Qatar",
    "Bosnia and Herzegovina",
    "Kenya",
    "S. Korea",
    "Zambia",
    "Nigeria",
    "Algeria",
    "Mongolia",
    "Kyrgyzstan",
    "North Macedonia",
    "Vietnam",
    "Afghanistan",
    "Latvia",
    "Norway",
    "Estonia",
    "Albania",
    "Uzbekistan",
    "Mozambique",
    "Namibia",
    "Zimbabwe",
    "Finland",
    "Botswana",
    "Ghana",
    "Cyprus",
    "Montenegro",
    "Uganda",
    "China",
    "El Salvador",
    "Cameroon",
    "Cambodia",
    "Maldives",
    "Luxembourg",
    "Rwanda",
    "Singapore",
    "Senegal",
    "Jamaica",
    "Malawi",
    "Ivory Coast",
    "DRC",
    "Angola",
    "Madagascar",
    "Trinidad and Tobago",
    "Réunion",
    "Sudan",
    "Australia",
    "Malta",
    "Cabo Verde",
    "Fiji",
    "French Guiana",
    "Eswatini",
    "Syria",
    "Guinea",
    "Mauritania",
    "Gabon",
    "Suriname",
    "Guyana",
    "Haiti",
    "French Polynesia",
    "Guadeloupe",
    "Mayotte",
    "Martinique",
    "Seychelles",
    "Papua New Guinea",
    "Togo",
    "Taiwan",
    "Somalia",
    "Tajikistan",
    "Bahamas",
    "Andorra",
    "Mali",
    "Belize",
    "Curaçao",
    "Burkina Faso",
    "Congo",
    "Lesotho",
    "Hong Kong",
    "Aruba",
    "Djibouti",
    "South Sudan",
    "Timor-Leste",
    "Nicaragua",
    "Channel Islands",
    "Equatorial Guinea",
    "Benin",
    "Iceland",
    "Gambia",
    "CAR",
    "Burundi",
    "Yemen",
    "Laos",
    "Eritrea",
    "Sierra Leone",
    "Niger",
    "Saint Lucia",
    "Liberia",
    "San Marino",
    "Gibraltar",
    "Chad",
    "Isle of Man",
    "Guinea-Bissau",
    "Barbados",
    "Comoros",
    "Mauritius",
    "Liechtenstein",
    "Monaco",
    "New Zealand",
    "Sint Maarten",
    "Saint Martin",
    "Bermuda",
    "Bhutan",
    "British Virgin Islands",
    "Turks and Caicos",
    "Sao Tome and Principe",
    "St. Vincent Grenadines",
    "Caribbean Netherlands",
    "Antigua and Barbuda",
    "St. Barth",
    "Tanzania",
    "Faeroe Islands",
    "Diamond Princess",
    "Cayman Islands",
    "Saint Kitts and Nevis",
    "Wallis and Futuna",
    "Brunei",
    "Dominica",
    "Grenada",
    "New Caledonia",
    "Greenland",
    "Anguilla",
    "Falkland Islands",
    "Macao",
    "Saint Pierre Miquelon",
    "Vatican City",
    "Montserrat",
    "Solomon Islands",
    "Western Sahara",
    "MS Zaandam",
    "Vanuatu",
    "Marshall Islands",
    "Samoa",
    "Saint Helena",
    "Micronesia"
  ];

  @override
  List<Widget> buildActions(BuildContext context) {
    return [
      IconButton(
        onPressed: () {
          query = '';
        },
        icon: Icon(Icons.clear),
      )
    ];
  }

  @override
  Widget buildLeading(BuildContext context) {
    return IconButton(
      icon: Icon(Icons.arrow_back),
      onPressed: () {
        close(context, query);
      },
    );
  }

  @override
  Widget buildResults(BuildContext context) {
    return Container();
  }

  @override
  Widget buildSuggestions(BuildContext context) {
    final selectList = query.isEmpty
        ? countryList
        : countryList.where(
            (country) {
              final countryLower = country.toLowerCase();
              final countryQueryUpper = query.toLowerCase();

              return countryLower.startsWith(countryQueryUpper);
            },
          ).toList();

    return selectList.isEmpty
        ? Center(
            child: Text(
              'No country found!!',
              style: TextStyle(fontSize: 25, fontWeight: FontWeight.bold),
            ),
          )
        : ListView.builder(
            itemCount: selectList.length,
            itemBuilder: (context, index) {
              return ListTile(
                onTap: () {
                  close(context, selectList[index]);
                },
                title: Text(selectList[index]),
              );
            },
          );
  }
}
